---
jo:  # noqa var-naming[no-role-prefix]
  dir: jo-{{ jo_version }}
  tgz: jo-{{ jo_version }}.tar.gz
  src: https://github.com/jpmens/jo/releases/download/{{ jo_version }}/jo-{{ jo_version }}.tar.gz
