services:
  ubuntu:
    build:
      context: ./ansible
      dockerfile: Dockerfile.ubuntu
    volumes:
      - ./ansible:/app
    tty: true
    dns:
      - 8.8.8.8
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    command: "python3"
  codespace:
    build:
      context: ./ansible
      dockerfile: Dockerfile.codespace
    volumes:
      - .:/usr/local/src/dotfiles
    tty: true
    dns:
      - 8.8.8.8
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    command: "python"
