---
fonts:  # noqa var-naming[no-role-prefix]
  notofont:
    src: https://github.com/notofonts/noto-cjk/releases/download/Sans2.004/06_NotoSansCJKjp.zip
    zip: 06_NotoSansCJKjp.zip
  jetbrainsmono_nerdfont:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
    zip: JetBrainsMono.zip
  departuremono_nerdfont:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/DepartureMono.zip
    zip: DepartureMono.zip
