# datasource=github-releases depName=direnv/direnv
direnv_version: v2.35.0
# datasource=github-tags depName=git/git
git_version: v2.49.0
# dummy
jo_version: "1.9"
# dummy
q_version: 3.1.7
# dummy
tmux_version: "3.5"
# dummy
zsh_version: "5.9"
# datasource=github-releases depName=rhysd/actionlint
actionlint_version: v1.7.8
# datasource=github-releases depName=reviewdog/reviewdog
reviewdog_version: v0.20.3
# datasource=github-releases depName=duckdb/duckdb
duckdb_version: v1.4.2
# datasource=github-releases depName=asciinema/agg
agg_version: v1.5.0
# datasource=github-releases depName=cli/cli
gh_version: v2.83.1
# datasource=github-releases depName=jdx/mise
mise_version: v2025.11.6
