[tools]
node = '24.11.1'
ruby = '3.3.5'
go = '1.25.5'
gcloud = 'latest'
awscli = '2.32.2'
deno = 'latest'
jq = '1.8.1'
bat = '0.24.0'
delta = '0.18.2'
terraform = '1.14.0'
python = '3.14.0'
pipx = 'latest'
act = 'latest'
vim = 'latest'
peco = 'latest'
yq = 'latest'
uv = 'latest'
fillin = 'latest'
bun = 'latest'
eza = 'latest'
ubi = 'latest'
vivid = 'latest'
ripgrep = 'latest'
fzf = 'latest'
"npm:zx" = 'latest'
"npm:opencommit" = 'latest'
"npm:pnpm" = 'latest'
"npm:yarn" = 'latest'
"npm:@github/copilot" = 'latest'
"pipx:mycli" = 'latest'
"pipx:cheat" = 'latest'
"pipx:mkdocs" = 'latest'
"pipx:jc" = 'latest'
"pipx:visidata" = 'latest'
ollama = 'latest'
rust = 'latest'

[settings]
experimental = true

